spring:
  application:
    name: csv-stats-match-parser
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:csv-stats-match-parser}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
      specific.avro.reader: true
app:
  csv:
    allowed-root: ${CSV_ALLOWED_ROOT:/data/csv}
  kafka:
    topics:
      file-ready: ${KAFKA_FILE_READY_TOPIC:file.ready.match-summary}
      parsed-stats-match: ${KAFKA_PARSED_STATS_MATCH_TOPIC:stats-match.parsed}
      dlt: ${KAFKA_MATCH_PARSER_DLT_TOPIC:file.ready.match-summary.DLT}
    error:
      max-attempts: ${KAFKA_RETRY_MAX_ATTEMPTS:3}
      backoff-ms: ${KAFKA_RETRY_BACKOFF_MS:1000}
